// File generated from our OpenAPI spec by Scalar. See README.md for details.

import type { Command } from 'commander';
import SDK from '../sdk/index';
import { createProgram, type CliClientOptionDefinition, type CliCommandDefinition } from '../cli/runtime';
import { completions } from '../cli/completions';

const clientOptions = [
  {
    clientKey: 'bearerAuth',
    sdkKey: 'bearerAuth',
    name: 'bearer-auth',
    optionKey: 'bearerAuth',
    env: 'BEARER_AUTH',
    description: 'JWT Bearer token authentication',
    auth: true,
  },
  {
    clientKey: 'basicAuthUsername',
    sdkKey: 'basicAuthUsername',
    name: 'basic-auth-username',
    optionKey: 'basicAuthUsername',
    env: 'BASIC_AUTH_USERNAME',
    description: 'Basic HTTP authentication',
    auth: true,
  },
  {
    clientKey: 'basicAuthPassword',
    sdkKey: 'basicAuthPassword',
    name: 'basic-auth-password',
    optionKey: 'basicAuthPassword',
    env: 'BASIC_AUTH_PASSWORD',
    description: 'Basic HTTP authentication',
    auth: true,
  },
  {
    clientKey: 'apiKeyHeader',
    sdkKey: 'apiKeyHeader',
    name: 'api-key-header',
    optionKey: 'apiKeyHeader',
    env: 'API_KEY_HEADER',
    description: 'API key request header',
    auth: true,
  },
  {
    clientKey: 'apiKeyQuery',
    sdkKey: 'apiKeyQuery',
    name: 'api-key-query',
    optionKey: 'apiKeyQuery',
    env: 'API_KEY_QUERY',
    description: 'API key query parameter',
    auth: true,
  },
  {
    clientKey: 'apiKeyCookie',
    sdkKey: 'apiKeyCookie',
    name: 'api-key-cookie',
    optionKey: 'apiKeyCookie',
    env: 'API_KEY_COOKIE',
    description: 'API key browser cookie',
    auth: true,
  },
  {
    clientKey: 'oAuth2',
    sdkKey: 'oAuth2',
    name: 'o-auth2',
    optionKey: 'oAuth2',
    env: 'SCALAR_O_AUTH2',
    description: 'OAuth 2.0 authentication',
    auth: true,
  },
  {
    clientKey: 'openIDConnect',
    sdkKey: 'openIDConnect',
    name: 'open-id-connect',
    optionKey: 'openIdConnect',
    env: 'SCALAR_OPEN_ID_CONNECT',
    description: 'OpenID Connect Authentication',
    auth: true,
  },
] as const satisfies readonly CliClientOptionDefinition[];

const commands = [
  {
    resourcePath: ['planets'],
    commandPath: ['planets', 'list-all-data'],
    methodName: 'listAllData',
    summary: 'Get all planets',
    description:
      "It's easy to say you know them all, but do you really? Retrieve all the planets and check whether you missed one.",
    transport: 'http',
    iterable: false,
    callShape: 'params',
    positional: [],
    flags: [
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: false,
        description: 'The number of items to return',
        valueKind: 'integer',
      },
      {
        name: 'offset',
        optionKey: 'offset',
        paramKey: 'offset',
        location: 'query',
        required: false,
        description: 'The number of items to skip before starting to collect the result set',
        valueKind: 'integer',
      },
    ],
  },
  {
    resourcePath: ['planets'],
    commandPath: ['planets', 'create'],
    methodName: 'create',
    summary: 'Create a planet',
    description:
      "Time to play god and create a new planet. What do you think? Ah, don't think too much. What could go wrong anyway?",
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [],
    flags: [
      {
        name: 'name',
        optionKey: 'name',
        paramKey: 'name',
        location: 'body',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'description',
        optionKey: 'description',
        paramKey: 'description',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'type',
        optionKey: 'type',
        paramKey: 'type',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'habitability-index',
        optionKey: 'habitabilityIndex',
        paramKey: 'habitabilityIndex',
        location: 'body',
        required: false,
        description: 'A score from 0 to 1 indicating potential habitability',
        valueKind: 'number',
      },
      {
        name: 'physical-properties',
        optionKey: 'physicalProperties',
        paramKey: 'physicalProperties',
        location: 'body',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'physical-properties.mass',
        optionKey: 'physicalProperties.mass',
        paramKey: 'physicalProperties',
        location: 'body',
        required: false,
        description: 'Mass in Earth masses (must be greater than 0)',
        valueKind: 'number',
        objectPath: ['mass'],
      },
      {
        name: 'physical-properties.radius',
        optionKey: 'physicalProperties.radius',
        paramKey: 'physicalProperties',
        location: 'body',
        required: false,
        description: 'Radius in Earth radii (must be greater than 0)',
        valueKind: 'number',
        objectPath: ['radius'],
      },
      {
        name: 'physical-properties.gravity',
        optionKey: 'physicalProperties.gravity',
        paramKey: 'physicalProperties',
        location: 'body',
        required: false,
        description: 'Surface gravity in Earth g',
        valueKind: 'number',
        objectPath: ['gravity'],
      },
      {
        name: 'physical-properties.temperature',
        optionKey: 'physicalProperties.temperature',
        paramKey: 'physicalProperties',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['temperature'],
      },
      {
        name: 'physical-properties.temperature.min',
        optionKey: 'physicalProperties.temperature.min',
        paramKey: 'physicalProperties',
        location: 'body',
        required: false,
        description: 'Minimum temperature in Kelvin',
        valueKind: 'number',
        objectPath: ['temperature', 'min'],
      },
      {
        name: 'physical-properties.temperature.max',
        optionKey: 'physicalProperties.temperature.max',
        paramKey: 'physicalProperties',
        location: 'body',
        required: false,
        description: 'Maximum temperature in Kelvin',
        valueKind: 'number',
        objectPath: ['temperature', 'max'],
      },
      {
        name: 'physical-properties.temperature.average',
        optionKey: 'physicalProperties.temperature.average',
        paramKey: 'physicalProperties',
        location: 'body',
        required: false,
        description: 'Average temperature in Kelvin',
        valueKind: 'number',
        objectPath: ['temperature', 'average'],
      },
      {
        name: 'atmosphere',
        optionKey: 'atmosphere',
        paramKey: 'atmosphere',
        location: 'body',
        required: false,
        description: 'Atmospheric composition',
        valueKind: 'array',
        repeatable: true,
      },
      {
        name: 'discovered-at',
        optionKey: 'discoveredAt',
        paramKey: 'discoveredAt',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'image',
        optionKey: 'image',
        paramKey: 'image',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'satellite',
        optionKey: 'satellite',
        paramKey: 'satellites',
        location: 'body',
        required: false,
        valueKind: 'array',
        repeatable: true,
      },
      {
        name: 'creator',
        optionKey: 'creator',
        paramKey: 'creator',
        location: 'body',
        required: false,
        description: 'A user',
        valueKind: 'object',
      },
      {
        name: 'creator.id',
        optionKey: 'creator.id',
        paramKey: 'creator',
        location: 'body',
        required: false,
        valueKind: 'integer',
        objectPath: ['id'],
      },
      {
        name: 'creator.name',
        optionKey: 'creator.name',
        paramKey: 'creator',
        location: 'body',
        required: false,
        valueKind: 'string',
        objectPath: ['name'],
      },
      {
        name: 'tag',
        optionKey: 'tag',
        paramKey: 'tags',
        location: 'body',
        required: false,
        valueKind: 'array',
        repeatable: true,
      },
      {
        name: 'success-callback-url',
        optionKey: 'successCallbackUrl',
        paramKey: 'successCallbackUrl',
        location: 'body',
        required: false,
        description: 'URL which gets invoked upon a successful operation',
        valueKind: 'string',
      },
      {
        name: 'failure-callback-url',
        optionKey: 'failureCallbackUrl',
        paramKey: 'failureCallbackUrl',
        location: 'body',
        required: false,
        description: 'URL which gets invoked upon a failed operation',
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['planets'],
    commandPath: ['planets', 'retrieve'],
    methodName: 'retrieve',
    summary: 'Get a planet',
    description:
      "You'll better learn a little bit more about the planets. It might come in handy once space travel is available for everyone.",
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [
      {
        name: 'planet-id',
        optionKey: 'planetId',
        paramKey: 'planetId',
        location: 'path',
        required: true,
        description: 'The ID of the planet to get',
        valueKind: 'integer',
      },
    ],
    flags: [],
  },
  {
    resourcePath: ['planets'],
    commandPath: ['planets', 'update'],
    methodName: 'update',
    summary: 'Update a planet',
    description: "Sometimes you make mistakes, that's fine. No worries, you can update all planets.",
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [
      {
        name: 'planet-id',
        optionKey: 'planetId',
        paramKey: 'planetId',
        location: 'path',
        required: true,
        description: 'The ID of the planet to get',
        valueKind: 'integer',
      },
    ],
    flags: [
      {
        name: 'name',
        optionKey: 'name',
        paramKey: 'name',
        location: 'body',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'description',
        optionKey: 'description',
        paramKey: 'description',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'type',
        optionKey: 'type',
        paramKey: 'type',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'habitability-index',
        optionKey: 'habitabilityIndex',
        paramKey: 'habitabilityIndex',
        location: 'body',
        required: false,
        description: 'A score from 0 to 1 indicating potential habitability',
        valueKind: 'number',
      },
      {
        name: 'physical-properties',
        optionKey: 'physicalProperties',
        paramKey: 'physicalProperties',
        location: 'body',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'physical-properties.mass',
        optionKey: 'physicalProperties.mass',
        paramKey: 'physicalProperties',
        location: 'body',
        required: false,
        description: 'Mass in Earth masses (must be greater than 0)',
        valueKind: 'number',
        objectPath: ['mass'],
      },
      {
        name: 'physical-properties.radius',
        optionKey: 'physicalProperties.radius',
        paramKey: 'physicalProperties',
        location: 'body',
        required: false,
        description: 'Radius in Earth radii (must be greater than 0)',
        valueKind: 'number',
        objectPath: ['radius'],
      },
      {
        name: 'physical-properties.gravity',
        optionKey: 'physicalProperties.gravity',
        paramKey: 'physicalProperties',
        location: 'body',
        required: false,
        description: 'Surface gravity in Earth g',
        valueKind: 'number',
        objectPath: ['gravity'],
      },
      {
        name: 'physical-properties.temperature',
        optionKey: 'physicalProperties.temperature',
        paramKey: 'physicalProperties',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['temperature'],
      },
      {
        name: 'physical-properties.temperature.min',
        optionKey: 'physicalProperties.temperature.min',
        paramKey: 'physicalProperties',
        location: 'body',
        required: false,
        description: 'Minimum temperature in Kelvin',
        valueKind: 'number',
        objectPath: ['temperature', 'min'],
      },
      {
        name: 'physical-properties.temperature.max',
        optionKey: 'physicalProperties.temperature.max',
        paramKey: 'physicalProperties',
        location: 'body',
        required: false,
        description: 'Maximum temperature in Kelvin',
        valueKind: 'number',
        objectPath: ['temperature', 'max'],
      },
      {
        name: 'physical-properties.temperature.average',
        optionKey: 'physicalProperties.temperature.average',
        paramKey: 'physicalProperties',
        location: 'body',
        required: false,
        description: 'Average temperature in Kelvin',
        valueKind: 'number',
        objectPath: ['temperature', 'average'],
      },
      {
        name: 'atmosphere',
        optionKey: 'atmosphere',
        paramKey: 'atmosphere',
        location: 'body',
        required: false,
        description: 'Atmospheric composition',
        valueKind: 'array',
        repeatable: true,
      },
      {
        name: 'discovered-at',
        optionKey: 'discoveredAt',
        paramKey: 'discoveredAt',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'image',
        optionKey: 'image',
        paramKey: 'image',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'satellite',
        optionKey: 'satellite',
        paramKey: 'satellites',
        location: 'body',
        required: false,
        valueKind: 'array',
        repeatable: true,
      },
      {
        name: 'creator',
        optionKey: 'creator',
        paramKey: 'creator',
        location: 'body',
        required: false,
        description: 'A user',
        valueKind: 'object',
      },
      {
        name: 'creator.id',
        optionKey: 'creator.id',
        paramKey: 'creator',
        location: 'body',
        required: false,
        valueKind: 'integer',
        objectPath: ['id'],
      },
      {
        name: 'creator.name',
        optionKey: 'creator.name',
        paramKey: 'creator',
        location: 'body',
        required: false,
        valueKind: 'string',
        objectPath: ['name'],
      },
      {
        name: 'tag',
        optionKey: 'tag',
        paramKey: 'tags',
        location: 'body',
        required: false,
        valueKind: 'array',
        repeatable: true,
      },
      {
        name: 'success-callback-url',
        optionKey: 'successCallbackUrl',
        paramKey: 'successCallbackUrl',
        location: 'body',
        required: false,
        description: 'URL which gets invoked upon a successful operation',
        valueKind: 'string',
      },
      {
        name: 'failure-callback-url',
        optionKey: 'failureCallbackUrl',
        paramKey: 'failureCallbackUrl',
        location: 'body',
        required: false,
        description: 'URL which gets invoked upon a failed operation',
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['planets'],
    commandPath: ['planets', 'delete'],
    methodName: 'delete',
    summary: 'Delete a planet',
    description:
      'This endpoint was used to delete planets. Unfortunately, that caused a lot of trouble for planets with life. So, this endpoint is now deprecated and should not be used anymore.',
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [
      {
        name: 'planet-id',
        optionKey: 'planetId',
        paramKey: 'planetId',
        location: 'path',
        required: true,
        description: 'The ID of the planet to get',
        valueKind: 'integer',
      },
    ],
    flags: [],
  },
  {
    resourcePath: ['planets'],
    commandPath: ['planets', 'delte-image'],
    methodName: 'delteImage',
    summary: 'Upload an image to a planet',
    description: 'Got a crazy good photo of a planet? Share it with the world!',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [
      {
        name: 'planet-id',
        optionKey: 'planetId',
        paramKey: 'planetId',
        location: 'path',
        required: true,
        description: 'The ID of the planet to get',
        valueKind: 'integer',
      },
    ],
    flags: [
      {
        name: 'image',
        optionKey: 'image',
        paramKey: 'image',
        location: 'body',
        required: false,
        description: 'The image file to upload',
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['celestialBodies'],
    commandPath: ['celestial-bodies', 'create'],
    methodName: 'create',
    summary: 'Create a celestial body',
    description:
      'Stars, moons, comets, the occasional rogue asteroid — if it glows or drifts through the void, you can add it here.',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [],
    flags: [],
  },
  {
    resourcePath: ['authentication'],
    commandPath: ['authentication', 'create-user'],
    methodName: 'createUser',
    summary: 'Create a user',
    description: 'Time to create a user account, eh?',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [],
    flags: [
      {
        name: 'name',
        optionKey: 'name',
        paramKey: 'name',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'email',
        optionKey: 'email',
        paramKey: 'email',
        location: 'body',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'password',
        optionKey: 'password',
        paramKey: 'password',
        location: 'body',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['authentication'],
    commandPath: ['authentication', 'create-token'],
    methodName: 'createToken',
    summary: 'Get a token',
    description: 'Yeah, this is the boring security stuff. Just get your super secret token and move on.',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [],
    flags: [
      {
        name: 'email',
        optionKey: 'email',
        paramKey: 'email',
        location: 'body',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'password',
        optionKey: 'password',
        paramKey: 'password',
        location: 'body',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['authentication'],
    commandPath: ['authentication', 'list-me'],
    methodName: 'listMe',
    summary: 'Get authenticated user',
    description: "Find yourself they say. That's what you can do here.",
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [],
    flags: [],
  },
] as const satisfies readonly CliCommandDefinition[];

export const getProgram = (): Command =>
  createProgram({
    SDK,
    binaryName: 'galaxy',
    version: '0.2.1', // x-release-please-version
    description: 'CLI for Scalar Galaxy',
    defaultFormat: 'auto',
    defaultErrorFormat: 'auto',
    clientOptions,
    commands,
    completions,
  });
